### ISSUE TITLE
FormRequests are not included

### ISSUE THREAD

**Issue by adriandmitroca** [potsky/laravel-localization-helpers#13]
This package doesn't search for translation strings in `Http/Requests`.

Scenario:
When you are forced to write custom validation message for specified Form Requests, you override messages() method and write messages there. For example:

`public function messages()`
	`{`
		`return [`
			`'exists' => trans('password.E-mail doesn't exist in our database.')`
	`	];`
`	}`

Issue: This string isn't catched by `localization:missing` console command.

**Comment by potsky** [comment]
Hi,

it should work. Two ideas :

1 - Do not use any dot in your lemmas, dots are reserved by laravel for the array dot notation.

Change 

```
trans('password.E-mail doesn't exist in our database.')
```

to 

```
trans('password.E-mail doesn't exist in our database')
```

2 - You file is not in the default directories where the package tries to find lemmas. You can then change directories in the package configuration file.
