### ISSUE TITLE
Problem with backup when dot is in path

### ISSUE THREAD

**Issue by marvinschroeder** [potsky/laravel-localization-helpers#20]
We have a DOCUMENT_ROOT structure where the domain name is part of the path. For example: `/var/www/kd/domain.com/`

When the command :missing is backup'ing the files, we get an Error Exception because the path is incorrect and the permission is denied. The path generated by your script (preg_match) is like:
`/var/www/kd/domain.20160129_151020.php`

So i propose to change the generation of the backup directory with keeping in mind that there could be a doc root with a dot in the path.

**Comment by potsky** [comment]
Hi marvinschroeder,

Thank for reporting and fortunately you have a permission denied error !

I will check this right now and publish a fix.

**Comment by potsky** [comment]
Hi !

Ok it is fixed now, you can update the package with composer. Sorry for this ugly bug :-(

**Comment by marvinschroeder** [comment]
Thanks! It's working now! Great package!

**Comment by potsky** [comment]
Thank you!
