### ISSUE TITLE
_ide_helper

### ISSUE THREAD

**Issue by ju5tify** [potsky/laravel-localization-helpers#24]
Please remove _ide_helper.php from repository as it can interfere with main project's _ide_helper.php

**Comment by potsky** [comment]
Correct, it will be removed in next release.

**Comment by potsky** [comment]
Is it ok for you if it renamed as `_ide_helper.php.remove`? Is your IDE still use it to analyse code?

**Comment by ju5tify** [comment]
I guess you should put it to .gitignore as it is dynamically generated file
