### ISSUE TITLE
Build error when trying to install `potsky/microsoft-translator-php-sdk` as dependency

### ISSUE THREAD

**Issue by alariva** [potsky/laravel-localization-helpers#25]
Hi,

I'm getting a Travis build error when trying to install `potsky/microsoft-translator-php-sdk` as dependency of `potsky/laravel-localization-helpers`.

The error is as follows.

```
  - Installing potsky/microsoft-translator-php-sdk (v0.0.2)
    Downloading: Connecting...    Failed to download potsky/microsoft-translator-php-sdk from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing potsky/microsoft-translator-php-sdk (v0.0.2)
    Cloning f0d17b1b8716376dabc9a028f1c8e78523ac7e7f
    f0d17b1b8716376dabc9a028f1c8e78523ac7e7f is gone (history was rewritten?)
                                                                               
  [RuntimeException]                                                           
  Failed to execute git checkout 'f0d17b1b8716376dabc9a028f1c8e78523ac7e7f' -  
  - && git reset --hard 'f0d17b1b8716376dabc9a028f1c8e78523ac7e7f' --          
  fatal: reference is not a tree: f0d17b1b8716376dabc9a028f1c8e78523ac7e7f     
                                                                               
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

[Full Build Info](https://travis-ci.org/timegridio/timegrid/jobs/111724794)

Is there anything I can do from this end to install it successfully?

Thanks in advance!!

**Comment by alariva** [comment]
Maybe using a concrete version of `potsky/microsoft-translator-php-sdk` would fix it?

[Like so](https://github.com/alariva/laravel-localization-helpers/commit/499ea08a465a8fe6cca4b083fff743948275aec8)

**Comment by potsky** [comment]
Hi !

I cannot check this this week. If you cannot wait for next week, yes, use an explicit commit hash in composer. Use the last one of course in the master branch.

**Comment by potsky** [comment]
I just have updated the packagist repository, could you try again please ?

**Comment by alariva** [comment]
I think this is a good solution, but I'm not sure on how to achieve this, as the `potsky/microsoft-translator-php-sdk` is a dependency of `potsky/laravel-localization-helpers`, and I have no control over the `composer.json` that ships with `potsky/laravel-localization-helpers` package. Maybe I'm missing something. So far I managed to make the build by removing `potsky/laravel-localization-helpers`, to be re-added when fixed.

Thanks for the prompt reply.

**Comment by alariva** [comment]
Oh! Sure, I can check this out. Hold on tight ;)

**Comment by alariva** [comment]
Worked just [perfect](https://travis-ci.org/timegridio/timegrid/builds/111745989)!

Thanks for the support. By the way, I'm interested in knowing how got this fixed since I'm a newcomer package dev :)
