### ISSUE TITLE
Keep files if only date time would change

### ISSUE THREAD

**Issue by Remo** [potsky/laravel-localization-helpers#26]
I've got a number of projects with a lot of languages and several translation files. Whenever I update them, I get a ton of changes, most of them only get a new header info `Generated via "php artisan localization:missing" at 2016/03/07 15:19:58`.

Do you have any reason why we shouldn't ignore those files completely? I'd suggest to keep the previous date time to avoid having unnecessary long commit logs.

**Comment by potsky** [comment]
Hi !

Sorry I am a little bit swamped these days, I will try to take a look on this problem. Indeed it is annoying for version control commits.

**Comment by potsky** [comment]
Hi @Remo,

why don't you use the `--no-date` option to avoid this ?

**Comment by Remo** [comment]
@potsky because it would be nice to have the dates, but I guess I can just ignore them and use my git log. I think it just looks odd because the default settings aren't ideal in my opinion, they create lots of changes, but `--no-date` is fine I think

**Comment by potsky** [comment]
@Remo,

In fact, to be honest, I really don't know why I have put this date in lang files!

It has nothing to do here from a logical point of view. The date is handled by the file modification date or by the CVS but not by the file data itself...
