### ISSUE TITLE
"Unable to write file in directory..."

### ISSUE THREAD

**Issue by o-ndr** [potsky/laravel-localization-helpers#37]
(I am a beginner, bear with my silly questions please)
Hi,
I am running php artisan localization:missing, lemmas are being found in my views (I use trans()), but I ma getting the following message: "> Unable to write file in directory /home/vagrant/Code/fitl/resources/lang/en/shared". So no lang files are being created in target language subfolders. As you can tell, my app is on a Homestead virtual machine.
Thanks for your help.

**Comment by potsky** [comment]
Hello,

it seems your `/home/vagrant/Code/fitl/resources/lang/en/shared` folder has incorrect rights set. The current unix user who execute the `php artisan localization:missing` command cannot write in this directory.
