### ISSUE TITLE
Laravel 5.3 support

### ISSUE THREAD

**Issue by pifoux2000** [potsky/laravel-localization-helpers#41]
any plan to release it soon ? Or is there any work around to install it in a laravel 5.3 application?

**Comment by potsky** [comment]
I will release a new version these days. I can check the 5.3 version support by the way.

**Comment by potsky** [comment]
There is an error when you execute the command or you cannot install it ?

**Comment by pifoux2000** [comment]
Composer refuses to install it as laravel 5.2.* is required in the package composer.json file. I didn't manage to install it manually either. Great package by the way.

**Comment by imbrish** [comment]
I've been waiting for updates on this package for so long. Great to see you're back!

**Comment by potsky** [comment]
Hey :-) Thanx !

I was obliged to take a break for almost 6 months for private reasons. I had no more computer and no more time to answer. But I am back and I have bought a new powerbook so here we go! I just need to install all stuffs to develop and all my projects will be up to date. Stay tuned...

**Comment by potsky** [comment]
Hi @pifoux2000,

I just have pushed a new branch for Laravel 5.3.

You should require the package with this version match `2.4.*` in composer.

Can you tell me if it is ok on your installation please?

**Comment by pifoux2000** [comment]
Hi @potsky 

thank you very much it worked perfectly :-)

**Comment by potsky** [comment]
Cool!
