### ISSUE TITLE
How About Cognitive Service Integration

### ISSUE THREAD

**Issue by pentatonicfunk** [potsky/laravel-localization-helpers#60]
i heard microsoft plan to end subscription for datamarket and dataservice on 3/31/2017 and migrate to their new Cognitive Service
https://datamarket.azure.com/dataset/bing/microsofttranslator
is there any plan to integrate with it ?

**Comment by potsky** [comment]
Unfortunately no because I tried to sign up to the new service and credit card is now mandatory.

Sorry for this.
