### ISSUE TITLE
"Generated via "php artisan localization:missing" at xxx" not practical with version control

### ISSUE THREAD

**Issue by philippejadin** [potsky/laravel-localization-helpers#66]
Each time I run php artisan localization:missing, every file is updated with the "generated by" line.
Then version control (git) want to update all the lang files and I need to unstage manually each file.

Would be great to have an option to not add this "generated" line. Ideally in config so it can be made a default.

Is it a good idea? Intended behavior?

And thank you for the great tool btw

**Comment by potsky** [comment]
Read the doc ;-)

Use the —no-date argument or with the short syntax : 

php artisan localization:missing -d

It should save your commit history. Enjoy !

**Comment by philippejadin** [comment]
Oh my! Sorry for that :-/
